---
title: "Association of nutrition trajectory and outcomes in pediatric leukemia and lymphoma patients"
author: "Charles Phillips"
output: 
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  
***
Use this template to complete your project throughout the course. Your Final Project presentation in class will be based on the contents of this document. Replace the title/name and text below with your own, but leave the headers. 

### Overview
In this section, give a brief a description of your project and its goal, what data you are using to complete it, and what three faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.

The goal of this study is to utilize PEDSnet, a pediatric learning health system, to describe the weight loss and growth patterns in pediatric patients during cancer treatment for leukemia and lymphoma, identify the patients at greatest risk for malnutrition, and compare outcomes between subgroups of patients as defined by their nutritional status. PEDSnet contains electronic health record data from eight pediatric hospitals working together to form a pediatric learning health system. My central hypothesis is that multiple weight loss patterns exist within pediatric oncology and early onset undernutrition is associated with increased mortality, and higher resource utilization. 


### Introduction 
In the first paragraph, describe the problem addressed, its significance, and some background to motivate the problem.

In the second paragraph, explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

According to the National Cancer Institute’s Surveillance, Epidemiology, and End Results (SEER) Program, there are approximately 15,000 cases on childhood cancer annually and the rates are slowly increasing over time. SEER data was recently released for 2014 and the age-adjusted cancer rates for children under the age of 20 was at 18.4 cases per 100,000 people which was a record high in the United States.  The Children’s Oncology Group (COG) recognizes nutrition as a critical component of cancer care. Nutritional derangements, including being both underweight and overweight, are known to reduce survival and increase morbidity in pediatric malignancies. Additionally, nutritional derangements are extremely common, with up to three-fourths of children having some nutritional derangement at the time of diagnosis. Variation occurs between institutions regarding nutritional supports and this is further complicated by different indicators used to follow nutritional derangements between centers. Proactive, early nutritional support is known to improve weight and nutritional status but its effect on cancer-related outcomes is unknown. While there is consensus nutritional support is important, the timing and content of these interventions is not standard.  One landmark study has examined weight, height, and growth trajectories by broad cancer categories; however the study was limited in that no single group had more than 53 patients. Additionally, because the treatment intensity could have varied significantly within each of the assigned groups of “solid,” “hematological,” and “brain” tumors, it remains unclear if subpopulations within these groups behave very differently compared to the groups as a whole. This project will be the first to use trajectory modeling to determine what nutritional subpopulations exist for pediatric leukemia and lymphoma.

This project is interdisciplinary at both the clinical and methodologic level. Clinically, it merges developmental pediatrics, nutrition, and oncology. Methodologically, it applies group-based trajectory modeling with traditional epidemiologic research. I have benefited from methodologic discussions with statisticians including Dr. Yong Chen and researchers who have previously incorporated trajectory modeling including Dr. Chen Kenyon. I have also identified my planned R package for the trajectory modeling, traj. Clinically, this project has been discussed with a pediatric oncologist, Dr. Charles Bailey and a dietician, Elizabeth Smith. These discussions have led to focusing the project on leukemia and lymphoma and the selection of outcomes including mortality.


### Methods
In the first paragraph, describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 

Overview and Conceptual Framework
The conceptual model for this study begins with the premise that oncology patients comprise multiple subgroups with different nutritional and growth patterns. I hypothesized that maintaining age-appropriate growth trajectories are protective during cancer treatment and reduce regimen-related morbidity, both directly and through improved delivery of cancer therapy. Age-adjusted weight trajectories will be used as a proxy for nutritional status.

Data Source
PEDSnet will be the data source. PEDSnet is a pediatric clinical research network contianing cancer diagnoses, treatment, laboratory test data, weight, and BMI measurements for all admissions and clinic visits. Weight and BMI information will be converted to Z-scores and trended over time. 

Study Design 
I will perform a retrospective study of newly diagnosed pediatric oncology patients from 2011-2016. A pediatric oncology patient will be defined as being ≤21 years of age with a new cancer diagnosis for leukemia or lymphoma, and having received treatment at a PEDSnet hospital. Patients who do not receive chemotherapy and are treated with only surgery or radiation will be excluded, as their treatment intensity cannot be well measured in PEDSnet data. During the time period of interest from 2011-2016, I expect approximately 700 patients in PEDSnet to meet inclusion criteria. Weight trajectories will be followed for a 1-year period.

Specific Aim 1: Describe patterns of weight loss and growth in pediatric leukemia and lymphoma patients as indicators of nutritional status.

Hypothesis 1: Multiple distinct categories of nutritional status and weight loss exist for pediatric patients receiving cancer treatment

Weight and BMI Z-score values will be obtained from PEDSnet. The starting time point will be defined as the first day chemotherapy is administered. Z-scores will be tracked in units of days since diagnosis. Z-score trends over time will be described using group-based trajectory modeling (GBTM). GBTM uses trajectory subgroups to identify and characterize differential patterns of individual change over time.1 For GBTM, each individual is assumed to belong to 1 and only 1 group wherein each group has its own distinct trajectory.2 I will perform 2, 3, 4, 5, 6, 7 and 8-group solutions to identify the optimal number of weight, and BMI groups within pediatric cancer patients. The final model will be selected based on a combination of Bayesian information criterion and the size of the trajectory groups. To be of sufficient size, each group must contain at least 5% of the oncology population.2 At least one group is expected to show rapid weight loss after starting cancer therapy.

Specific Aim 2: Describe the physiologic and clinical characteristics of the patient population in the undernourished cohort(s) identified in Aim 1.  

Key demographic and disease co-variables previously shown to contribute to both oncologic disease complexity and clinical outcomes will be compared between the nutrition subgroups.3-6 The covariates along with a brief description are shown (Table 1). 

Table 1: Co-Variates
Co-variates                     Description                     Variable type
Cancer Diagnosis                Leukemia, lymphoma, etc.        Categorical
Sex                             Male, female                    Binary
Race                            Black, White, Asian, etc.       Categorical
Ethnicity                       Hispanic, non-Hispanic          Binary
Weight for age at diagnosis     Z score                         Continuous
Age at diagnosis                Years                           Continuous

Each nutritional subgroup will be characterized and compared to one another using both descriptive statistics and standard testing of multiple-group variance. 

Specific Aim 3 and 3B: Compare all-cause mortality by nutritional cohort.

Significant under and over nutrition are known to increase morbidity and mortality for pediatric cancer patients. It is not known how particular nutritional trajectories affect these risks, or whether risk is concentrated in a subset of the overall population.

Hypothesis 3: The most undernourished cohort has >5% increase in all-cause mortality compared to other cohorts.

A multivariate regression model will be used to describe the association between the malnutrition subpopulation and the outcome of interest, controlling for covariates. Nutrition subgroups were included as the primary predictor variable.

### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

Results
* patients met inclusion criteria. The demographic characteristics of the population are shown in Table 2.
Table 2: Demographics
Characteristics                         n (%)
Cancer Diagnosis
        Acute Lymphoid Leukemia
        Acute Myeloid Leukemia
        Hodgkin’s Lymphoma
        Non-Hodgkin’s Lymphoma
Sex
        Male
        Female
Race
        White
        Black
        Asian
        Unknown
Ethnicity
        Hispanic
        Non-Hispanic
Weight for age Z score at diagnosis (mean)
Age at diagnosis in years (mean)


Group-based trajectory modeling (GBTM) was performed using 2, 3, 4, 5, 6, 7 and 8-group solutions to identify the optimal number of weight, and BMI groups within pediatric leukemia and lymphoma patients. The Bayesian information criterion are shown (Table 3).

Table 3: Bayesian information criterion
Pre-specified Number of Subgroups       Bayesian information criterion
2
3
4
5
6
7
8

Key demographic features were analyzed by nutritional subgroup (Table 4).
Table 4: Demographic features by nutritional subgroup.
Characteristics Lose weight n (%)       Stable weight n (%)     Gain weight n (%)
Cancer Diagnosis
        Acute Lymphoid Leukemia
        Acute Myeloid Leukemia
        Hodgkin’s Lymphoma
        Non-Hodgkin’s Lymphoma
Sex
        Male
        Female
Race
        White
        Black
        Asian
        Unknown
Ethnicity
        Hispanic
        Non-Hispanic
Weight for age Z score at diagnosis (mean)
Age at diagnosis in years (mean)

After controlling for covariates, all-cause mortality was (not) statistically significant between the * nutrition subgroups. All-cause mortality rate was * in the weight loss group, * in the stable rate group, and * in the gain weight group. 

### References
1.	Modi AC, Rausch JR, Glauser TA. Patterns of nonadherence to antiepileptic drug therapy in children with newly diagnosed epilepsy. Jama. 2011;305(16):1669-1676.
2.	Nagin DS, Odgers CL. Group-based trajectory modeling in clinical research. Annual review of clinical psychology. 2010;6:109-138.
3.	Bhatia S. Disparities in cancer outcomes: lessons learned from children with cancer. Pediatric blood & cancer. 2011;56(6):994-1002.
4.	Seif AE, Fisher BT, Li Y, et al. Patient and hospital factors associated with induction mortality in acute lymphoblastic leukemia. Pediatric blood & cancer. 2014;61(5):846-852.
5.	Wang L, Bhatia S, Gomez SL, Yasui Y. Differential inequality trends over time in survival among U.S. children with acute lymphoblastic leukemia by race/ethnicity, age at diagnosis, and sex. Cancer epidemiology, biomarkers & prevention : a publication of the American Association for Cancer Research, cosponsored by the American Society of Preventive Oncology. 2015;24(11):1781-1788.
6.	Co-Reyes E, Li R, Huh W, Chandra J. Malnutrition and obesity in pediatric oncology patients: causes, consequences, and interventions. Pediatric blood & cancer. 2012;59(7):1160-1167.


